import type { Metadata } from "next";
import Header from "@/components/Header";
import Footer from "@/components/Footer";

export const metadata: Metadata = {
  title: "Terms of Service — AltShot",
  description:
    "Terms and conditions for using AltShot, the AI-powered image SEO optimization app for Shopify stores.",
};

export default function TermsOfService() {
  return (
    <>
      <Header />
      <main className="flex-1 bg-white">
        <div className="max-w-3xl mx-auto px-4 sm:px-6 lg:px-8 py-16 sm:py-24">
          <h1 className="text-4xl font-extrabold bg-gradient-to-r from-[#9b6cc4] via-[#6a7fd8] to-[#3b82f6] bg-clip-text text-transparent mb-2">
            Terms of Service
          </h1>
          <p className="text-sm text-muted mb-12">
            Last updated: April 20, 2026
          </p>

          <div className="space-y-10 text-foreground leading-relaxed">
            <section>
              <h2 className="text-2xl font-bold mb-4">
                Acceptance of Terms
              </h2>
              <p>
                By installing, accessing, or using AltShot (&quot;the
                App&quot;), you agree to be bound by these Terms of Service
                (&quot;Terms&quot;). If you do not agree to these Terms, do not
                install or use the App. These Terms apply to all users of the
                App, including Shopify store owners and authorized users.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-bold mb-4">
                Description of Service
              </h2>
              <p>
                AltShot is an AI-powered image SEO optimization app for Shopify
                stores. Our service includes:
              </p>
              <ul className="list-disc pl-6 space-y-2 mt-3">
                <li>
                  Automated AI-generated alt text for product images
                </li>
                <li>Image compression and optimization</li>
                <li>Filename optimization for SEO</li>
                <li>Image SEO scoring and reporting</li>
                <li>Bulk image processing tools</li>
              </ul>
            </section>

            <section>
              <h2 className="text-2xl font-bold mb-4">Account and Access</h2>
              <p>
                To use AltShot, you must have an active Shopify store. The App
                is accessed exclusively through the Shopify admin interface.
                You are responsible for maintaining the security of your
                Shopify account and for all activities that occur under your
                account.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-bold mb-4">Plans and Billing</h2>
              <p className="mb-3">
                AltShot offers the following subscription plans:
              </p>
              <ul className="list-disc pl-6 space-y-2">
                <li>
                  <strong>Free</strong> — 50 images per month, no charge
                </li>
                <li>
                  <strong>Starter</strong> — 500 images per month at $4.99/month
                </li>
                <li>
                  <strong>Pro</strong> — Unlimited images at $9.99/month
                </li>
              </ul>
              <p className="mt-4">
                All paid subscriptions are billed through Shopify&apos;s billing
                system. By subscribing to a paid plan, you authorize Shopify to
                charge your account according to the selected plan. Pricing is
                subject to change with notice.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-bold mb-4">Usage Limits</h2>
              <p>
                Each plan includes a monthly image processing quota. Quotas
                reset at the beginning of each billing cycle. Unused images do
                not roll over to the next billing cycle. If you reach your
                monthly limit, you can upgrade your plan to continue processing
                images.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-bold mb-4">
                AI-Generated Content
              </h2>
              <p>
                Alt text generated by AltShot is produced using artificial
                intelligence and is provided as a suggestion. You, the
                merchant, are solely responsible for reviewing and approving all
                AI-generated alt text before applying it to your store.
              </p>
              <p className="mt-3">
                We do not guarantee that AI-generated alt text will improve your
                search engine rankings or SEO performance. Results may vary
                depending on your store, products, and other factors outside our
                control.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-bold mb-4">Image Compression</h2>
              <p>
                When you use AltShot&apos;s image compression feature,
                compressed images replace the original images on your Shopify
                store. Existing alt text is preserved during compression.
              </p>
              <p className="mt-3 font-semibold">
                Image compression is irreversible. Once an image is compressed
                and uploaded, the original file cannot be restored through
                AltShot. We strongly recommend that merchants keep backups of
                their original images before using the compression feature.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-bold mb-4">
                Intellectual Property
              </h2>
              <p>
                You retain all rights to your product images, content, and
                store data. AI-generated alt text is provided to you as part of
                the service and you are free to use, modify, or discard it as
                you see fit. AltShot retains ownership of the App, its code,
                design, and underlying technology.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-bold mb-4">Prohibited Uses</h2>
              <p className="mb-3">You agree not to:</p>
              <ul className="list-disc pl-6 space-y-2">
                <li>
                  Abuse, overload, or interfere with the AltShot API or
                  infrastructure
                </li>
                <li>
                  Use the App for any illegal, fraudulent, or unauthorized
                  purpose
                </li>
                <li>
                  Attempt to reverse-engineer, decompile, or extract the source
                  code of the App
                </li>
                <li>
                  Resell, sublicense, or redistribute access to the App
                </li>
                <li>
                  Use automated tools to scrape or extract data from the App
                  beyond normal usage
                </li>
              </ul>
            </section>

            <section>
              <h2 className="text-2xl font-bold mb-4">
                Limitation of Liability
              </h2>
              <p>
                To the maximum extent permitted by applicable law, AltShot and
                its operators shall not be liable for any indirect, incidental,
                special, consequential, or punitive damages, or any loss of
                profits or revenue, whether incurred directly or indirectly, or
                any loss of data, use, goodwill, or other intangible losses
                resulting from:
              </p>
              <ul className="list-disc pl-6 space-y-2 mt-3">
                <li>Your use of or inability to use the App</li>
                <li>
                  Any changes made to your store&apos;s images or content
                  through the App
                </li>
                <li>
                  Unauthorized access to or alteration of your data
                </li>
                <li>
                  Any third-party conduct or content related to the App
                </li>
              </ul>
              <p className="mt-4">
                In no event shall our total liability exceed the amount you
                paid to us in the twelve (12) months preceding the claim.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-bold mb-4">Termination</h2>
              <p>
                Either party may terminate this agreement at any time. You may
                terminate by uninstalling the App from your Shopify store. We
                may terminate or suspend your access if you violate these
                Terms.
              </p>
              <p className="mt-3">
                Upon uninstallation, your access to the App is immediately
                revoked. All associated shop data will be deleted from our
                systems within 30 days of uninstallation.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-bold mb-4">Governing Law</h2>
              <p>
                These Terms shall be governed by and construed in accordance
                with the laws of the United Kingdom, without regard to
                conflict-of-law principles. Any disputes arising under these
                Terms shall be subject to the exclusive jurisdiction of the
                courts of the United Kingdom.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-bold mb-4">
                Changes to These Terms
              </h2>
              <p>
                We reserve the right to modify these Terms at any time. If we
                make material changes, we will notify you through the AltShot
                app dashboard. Your continued use of the App after changes are
                posted constitutes acceptance of the revised Terms.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-bold mb-4">Contact Us</h2>
              <p>
                If you have any questions about these Terms of Service, please
                contact us at{" "}
                <a
                  href="mailto:support@altshot.co"
                  className="text-primary hover:underline font-medium"
                >
                  support@altshot.co
                </a>
                .
              </p>
            </section>
          </div>
        </div>
      </main>
      <Footer />
    </>
  );
}
